version: '3.1'
services:
  web:
    build: .
    ports:
      - "8080:5000" 
    secrets:
      - secret_key
      - admin_password
    volumes:
      - .:/home/spell_check

secrets:
  secret_key:
    file: /run/secrets/secret_key
  admin_password:
    file: /run/secrets/admin_password
