version: '3.1'
services:
  web:
    build: .
    image: spell_check
    ports:
      - "8080:5000" 
    volumes:
      - .:/home/spell_check
    secrets:
      - secret_key
    deploy:
      resources:
        limits:
            cpus: '0.50'
            memory: 100MB
      replicas: 4

secrets:
  secret_key:
    file: secrets/secret_key.secrets
