version: '3.1'
services:
  web:
    build: .
    ports:
      - "8080:5000" 
    volumes:
      - .:/home/spell_check
    secrets:
      - secret_key

secrets:
  secret_key:
    file: secrets/secret_key.secrets
